import type { CreateApplicationInput } from './types';

export const SEED_APPLICATIONS: CreateApplicationInput[] = [
  {
    company: 'Atlassian',
    position: 'Full Stack Software Engineer',
    date_applied: '2026-05-12',
    status: 'Interview',
    source: 'LinkedIn',
    location: 'Sydney, NSW',
    work_type: 'Hybrid',
    role_type: 'Full Stack',
    salary_min: 130000,
    salary_max: 160000,
    job_url: 'https://www.linkedin.com/jobs/view/atlassian-full-stack-engineer-sydney',
    follow_up_date: '2026-06-20',
    last_contact_date: '2026-06-15',
    priority: 'High',
    next_action: 'Prepare system design for round 2 interview',
    notes:
      'Technical screen passed. Round 2 is system design + culture fit. Stack: React, Node.js, Java microservices.',
  },
  {
    company: 'Canva',
    position: 'Frontend Engineer',
    date_applied: '2026-05-28',
    status: 'In Review',
    source: 'LinkedIn',
    location: 'Sydney, NSW',
    work_type: 'Hybrid',
    role_type: 'Frontend',
    salary_min: 125000,
    salary_max: 155000,
    job_url: 'https://www.linkedin.com/jobs/view/canva-frontend-engineer',
    follow_up_date: '2026-07-08',
    priority: 'High',
    next_action: 'Follow up if no response by July 8',
    notes: 'Applied via LinkedIn Easy Apply. Strong match with React/TypeScript experience.',
  },
  {
    company: 'REA Group',
    position: 'Senior Frontend Developer',
    date_applied: '2026-06-01',
    status: 'Applied',
    source: 'Seek',
    location: 'Melbourne, VIC',
    work_type: 'Hybrid',
    role_type: 'Frontend',
    salary_min: 140000,
    salary_max: 170000,
    job_url: 'https://www.seek.com.au/job/rea-group-senior-frontend-developer',
    follow_up_date: '2026-07-08',
    priority: 'Medium',
    next_action: 'Send follow-up email to recruiter',
    notes: 'realestate.com.au team. Requires React, TypeScript, accessibility standards.',
  },
  {
    company: 'Xero',
    position: 'Full Stack Engineer',
    date_applied: '2026-06-05',
    status: 'Applied',
    source: 'Company Website',
    location: 'Melbourne, VIC',
    work_type: 'Hybrid',
    role_type: 'Full Stack',
    salary_min: 120000,
    salary_max: 150000,
    job_url: 'https://www.xero.com/careers/full-stack-engineer-melbourne',
    follow_up_date: '2026-07-10',
    priority: 'Medium',
    next_action: 'Follow up after 7 business days',
    notes: 'Applied through Xero careers portal. C#/.NET backend with React frontend.',
  },
  {
    company: 'Culture Amp',
    position: 'PHP Developer',
    date_applied: '2026-04-20',
    status: 'Rejected',
    source: 'Seek',
    location: 'Melbourne, VIC',
    work_type: 'Remote',
    role_type: 'PHP',
    salary_min: 110000,
    salary_max: 140000,
    job_url: 'https://www.seek.com.au/job/culture-amp-php-developer',
    last_contact_date: '2026-05-10',
    priority: 'Low',
    notes: 'Rejected after phone screen. Feedback: need more Laravel experience at scale.',
  },
  {
    company: 'Automattic',
    position: 'WordPress Developer',
    date_applied: '2026-06-08',
    status: 'Assessment',
    source: 'LinkedIn',
    location: 'Remote (AU)',
    work_type: 'Remote',
    role_type: 'WordPress',
    salary_min: 100000,
    salary_max: 130000,
    job_url: 'https://www.linkedin.com/jobs/view/automattic-wordpress-developer',
    follow_up_date: '2026-07-05',
    last_contact_date: '2026-06-18',
    priority: 'High',
    next_action: 'Complete take-home WordPress plugin assignment by Friday',
    notes: 'Received take-home: build a Gutenberg block plugin. Due in 5 days.',
  },
  {
    company: 'WP Engine',
    position: 'Senior WordPress Developer',
    date_applied: '2026-06-10',
    status: 'Saved',
    source: 'LinkedIn',
    location: 'Remote (APAC)',
    work_type: 'Remote',
    role_type: 'WordPress',
    salary_min: 115000,
    salary_max: 145000,
    job_url: 'https://www.linkedin.com/jobs/view/wp-engine-senior-wordpress-developer',
    priority: 'Medium',
    next_action: 'Tailor resume for WordPress hosting experience and apply',
    notes: 'Bookmarked — need to customize cover letter highlighting managed WordPress hosting work.',
  },
  {
    company: 'Deakin University',
    position: 'WordPress Developer',
    date_applied: '2026-05-22',
    status: 'No Response',
    source: 'Seek',
    location: 'Melbourne, VIC',
    work_type: 'On-site',
    role_type: 'WordPress',
    salary_min: 85000,
    salary_max: 95000,
    job_url: 'https://www.seek.com.au/job/deakin-university-wordpress-developer',
    follow_up_date: '2026-06-15',
    priority: 'Low',
    next_action: 'Archive — no response after 2 follow-ups',
    notes: 'Applied 6 weeks ago. Sent 2 follow-ups with no reply. Mark as ghosted.',
  },
  {
    company: 'Nine Entertainment',
    position: 'Frontend Developer',
    date_applied: '2026-05-15',
    status: 'No Response',
    source: 'Seek',
    location: 'Sydney, NSW',
    work_type: 'Hybrid',
    role_type: 'Frontend',
    salary_min: 110000,
    salary_max: 130000,
    job_url: 'https://www.seek.com.au/job/nine-entertainment-frontend-developer',
    priority: 'Low',
    notes: 'No response after 21+ days. Likely high competition for media company role.',
  },
  {
    company: 'Telstra',
    position: 'Full Stack Developer',
    date_applied: '2026-06-02',
    status: 'In Review',
    source: 'LinkedIn',
    location: 'Melbourne, VIC',
    work_type: 'Hybrid',
    role_type: 'Full Stack',
    salary_min: 115000,
    salary_max: 140000,
    job_url: 'https://www.linkedin.com/jobs/view/telstra-full-stack-developer',
    follow_up_date: '2026-07-09',
    last_contact_date: '2026-06-12',
    contact_name: 'Sarah Chen',
    priority: 'Medium',
    next_action: 'Recruiter reviewing — expect update by next week',
    notes: 'Recruiter Sarah confirmed application is with hiring manager. Angular + Java stack.',
  },
  {
    company: 'Commonwealth Bank',
    position: 'Senior PHP Developer',
    date_applied: '2026-05-18',
    status: 'Interview',
    source: 'LinkedIn',
    location: 'Sydney, NSW',
    work_type: 'Hybrid',
    role_type: 'PHP',
    salary_min: 135000,
    salary_max: 165000,
    job_url: 'https://www.linkedin.com/jobs/view/commbank-senior-php-developer',
    follow_up_date: '2026-06-25',
    last_contact_date: '2026-06-20',
    contact_name: 'James Morrison',
    priority: 'High',
    next_action: 'Panel interview on June 25 — review Symfony patterns',
    notes: 'Passed coding challenge. Panel interview with 2 senior engineers + hiring manager.',
  },
  {
    company: 'Accenture Australia',
    position: 'Full Stack Developer',
    date_applied: '2026-04-28',
    status: 'Rejected',
    source: 'Seek',
    location: 'Sydney, NSW',
    work_type: 'Hybrid',
    role_type: 'Full Stack',
    salary_min: 100000,
    salary_max: 130000,
    job_url: 'https://www.seek.com.au/job/accenture-full-stack-developer-sydney',
    last_contact_date: '2026-05-20',
    priority: 'Low',
    notes: 'Rejected after technical assessment. Case study presentation needed improvement.',
  },
  {
    company: 'Seek Limited',
    position: 'Frontend Engineer',
    date_applied: '2026-06-12',
    status: 'Applied',
    source: 'Company Website',
    location: 'Melbourne, VIC',
    work_type: 'Hybrid',
    role_type: 'Frontend',
    salary_min: 120000,
    salary_max: 150000,
    job_url: 'https://www.seek.com.au/careers/frontend-engineer',
    follow_up_date: '2026-07-15',
    priority: 'High',
    next_action: 'Follow up in 7 days if no response',
    notes: 'Applied directly on Seek careers page. React, TypeScript, design system experience required.',
  },
  {
    company: 'Envato',
    position: 'WordPress Theme Developer',
    date_applied: '2026-05-05',
    status: 'Offer',
    source: 'LinkedIn',
    location: 'Melbourne, VIC',
    work_type: 'Remote',
    role_type: 'WordPress',
    salary_min: 105000,
    salary_max: 125000,
    job_url: 'https://www.linkedin.com/jobs/view/envato-wordpress-theme-developer',
    last_contact_date: '2026-06-18',
    contact_name: 'Lisa Park',
    contact_email: 'lisa.park@envato.com',
    priority: 'High',
    next_action: 'Review offer letter — negotiate start date',
    notes: 'Offer received: $118k AUD + super. 4 weeks notice period. Considering alongside other offers.',
  },
  {
    company: 'MYOB',
    position: 'PHP Developer',
    date_applied: '2026-05-08',
    status: 'Withdrawn',
    source: 'Seek',
    location: 'Melbourne, VIC',
    work_type: 'Hybrid',
    role_type: 'PHP',
    salary_min: 100000,
    salary_max: 120000,
    job_url: 'https://www.seek.com.au/job/myob-php-developer',
    last_contact_date: '2026-05-25',
    priority: 'Low',
    notes: 'Withdrew after accepting another process. Small team, legacy PHP codebase concerns.',
  },
  {
    company: 'SiteGround',
    position: 'Senior WordPress Developer',
    date_applied: '2026-06-15',
    status: 'Applied',
    source: 'LinkedIn',
    location: 'Remote (Global)',
    work_type: 'Remote',
    role_type: 'WordPress',
    salary_min: 90000,
    salary_max: 110000,
    job_url: 'https://www.linkedin.com/jobs/view/siteground-wordpress-developer',
    follow_up_date: '2026-07-15',
    priority: 'Medium',
    next_action: 'Monitor inbox — applied 3 days ago',
    notes: 'Remote WordPress hosting company. PHP, WordPress core, plugin development focus.',
  },
];
